from django.db import models

# Create your models here.
# TODO MODEL FOR POSTS THEY WILL BE THE SAME< USE THE SAME MODEL FOR BOTH BOASTS AND ROASTS
# DONT FORGET TO REGISTER IN ADMIN AND THEN MIGRATE